// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL66UKi29nuKviLtL_CkOgt_n7SKQ5eKk',
    appId: '1:114786248598:web:d951fc3cbd8e108e4b5fb7',
    messagingSenderId: '114786248598',
    projectId: 'maf-carrefour-c49d8',
    authDomain: 'maf-carrefour-c49d8.firebaseapp.com',
    storageBucket: 'maf-carrefour-c49d8.appspot.com',
    measurementId: 'G-BEGSJS91LK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvxoaTgD6EgCQC0haGW69i5yVOlNEdYUg',
    appId: '1:114786248598:android:626e20734c19bdb04b5fb7',
    messagingSenderId: '114786248598',
    projectId: 'maf-carrefour-c49d8',
    storageBucket: 'maf-carrefour-c49d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9vIoc0BOn_H4psNOQVtLg0P-zVIg2jKI',
    appId: '1:114786248598:ios:19f370c957fff1544b5fb7',
    messagingSenderId: '114786248598',
    projectId: 'maf-carrefour-c49d8',
    storageBucket: 'maf-carrefour-c49d8.appspot.com',
    iosClientId: '114786248598-uh7ud7hojvknkuruqi98uo4hrtthtd3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.mafCarrefour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9vIoc0BOn_H4psNOQVtLg0P-zVIg2jKI',
    appId: '1:114786248598:ios:19f370c957fff1544b5fb7',
    messagingSenderId: '114786248598',
    projectId: 'maf-carrefour-c49d8',
    storageBucket: 'maf-carrefour-c49d8.appspot.com',
    iosClientId: '114786248598-uh7ud7hojvknkuruqi98uo4hrtthtd3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.mafCarrefour',
  );
}
